### ISSUE TITLE
Allow other curated awesome lists to be part of current list separately 

### ISSUE THREAD

**Issue by adilwahla** [ykdojo/active-repos-for-contributing#22]
## Suggestion 01
#14 check out #21 you will see github has fewer other [Repos](https://github.com/MunGell/awesome-for-beginners) that are serving same purpose Shouldn't we add such lists in separate space ? 
## Suggestion 02
Give a well organized look for quicker reach to relevant projects ...bcz we want contributions at once by beginners :)
1. Add table of content at top
2. list languages/tech stack
3. list projects 

![Screenshot (21)](https://user-images.githubusercontent.com/48839911/193405320-85881f06-ba50-4fb9-a333-7a6f1fca1cee.png)

![Screenshot (20)](https://user-images.githubusercontent.com/48839911/193405332-972de0da-1797-4336-bae5-8b77990fad8e.png)

@ykdojo what do you think ?

**Comment by ykdojo** [comment]
First of all, the two suggestions should be separate issues. Would you mind creating a separate one for your second suggestion?

For the first one, as I mentioned in #21, I don't think we should have lists within this list to keep it simpler to maintain.

**Comment by adilwahla** [comment]
sure you are right i guess simplicity is much required
